version: '2'
services:
    chsp-app:
        image: chsp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://chsp-postgresql:5432/chsp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    chsp-postgresql:
        extends:
            file: postgresql.yml
            service: chsp-postgresql
